//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 09:10:28 PM IST 
//


package com.capgemini.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.capgemini.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.capgemini.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Request.SearchData }
     * 
     */
    public Request.SearchData createRequestSearchData() {
        return new Request.SearchData();
    }

    /**
     * Create an instance of {@link Request.SearchData.Directors }
     * 
     */
    public Request.SearchData.Directors createRequestSearchDataDirectors() {
        return new Request.SearchData.Directors();
    }

    /**
     * Create an instance of {@link Request.SearchData.Directors.Director }
     * 
     */
    public Request.SearchData.Directors.Director createRequestSearchDataDirectorsDirector() {
        return new Request.SearchData.Directors.Director();
    }

    /**
     * Create an instance of {@link Request.SearchData.Contact }
     * 
     */
    public Request.SearchData.Contact createRequestSearchDataContact() {
        return new Request.SearchData.Contact();
    }

    /**
     * Create an instance of {@link Request.Header }
     * 
     */
    public Request.Header createRequestHeader() {
        return new Request.Header();
    }

    /**
     * Create an instance of {@link Request.SearchData.GeneralFields }
     * 
     */
    public Request.SearchData.GeneralFields createRequestSearchDataGeneralFields() {
        return new Request.SearchData.GeneralFields();
    }

    /**
     * Create an instance of {@link Request.SearchData.CompanyName }
     * 
     */
    public Request.SearchData.CompanyName createRequestSearchDataCompanyName() {
        return new Request.SearchData.CompanyName();
    }

    /**
     * Create an instance of {@link Request.SearchData.Id }
     * 
     */
    public Request.SearchData.Id createRequestSearchDataId() {
        return new Request.SearchData.Id();
    }

    /**
     * Create an instance of {@link Request.SearchData.Directors.Director.Address }
     * 
     */
    public Request.SearchData.Directors.Director.Address createRequestSearchDataDirectorsDirectorAddress() {
        return new Request.SearchData.Directors.Director.Address();
    }

    /**
     * Create an instance of {@link Request.SearchData.Directors.Director.Telephone }
     * 
     */
    public Request.SearchData.Directors.Director.Telephone createRequestSearchDataDirectorsDirectorTelephone() {
        return new Request.SearchData.Directors.Director.Telephone();
    }

    /**
     * Create an instance of {@link Request.SearchData.Contact.Address }
     * 
     */
    public Request.SearchData.Contact.Address createRequestSearchDataContactAddress() {
        return new Request.SearchData.Contact.Address();
    }

    /**
     * Create an instance of {@link Request.SearchData.Contact.Telephone }
     * 
     */
    public Request.SearchData.Contact.Telephone createRequestSearchDataContactTelephone() {
        return new Request.SearchData.Contact.Telephone();
    }

}
