//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 09:10:28 PM IST 
//


package com.capgemini.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="product_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="user_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="member_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="member_KOB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="member_reference_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="report_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="output_format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="search_data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="general_fields">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="enquiry_amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="enquiry_purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="enquiry_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="type_of_entity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="class_of_activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="date_of_registration" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cmr_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="company_name">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="id">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="crn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="contact">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="address" maxOccurs="3">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="telephone" maxOccurs="3" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="directors">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="director" maxOccurs="3" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="relation_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="voter_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="passport_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="driving_licence_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="address">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="telephone" maxOccurs="3" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "searchData"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    protected Request.Header header;
    @XmlElement(name = "search_data", required = true)
    protected Request.SearchData searchData;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Request.Header }
     *     
     */
    public Request.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.Header }
     *     
     */
    public void setHeader(Request.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the searchData property.
     * 
     * @return
     *     possible object is
     *     {@link Request.SearchData }
     *     
     */
    public Request.SearchData getSearchData() {
        return searchData;
    }

    /**
     * Sets the value of the searchData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request.SearchData }
     *     
     */
    public void setSearchData(Request.SearchData value) {
        this.searchData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="product_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="user_password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="member_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="member_KOB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="member_reference_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="report_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="output_format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version",
        "productType",
        "userId",
        "userPassword",
        "memberCode",
        "memberKOB",
        "memberReferenceNumber",
        "reportType",
        "outputFormat"
    })
    public static class Header {

        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "product_type", required = true)
        protected String productType;
        @XmlElement(name = "user_id", required = true)
        protected String userId;
        @XmlElement(name = "user_password", required = true)
        protected String userPassword;
        @XmlElement(name = "member_code", required = true)
        protected String memberCode;
        @XmlElement(name = "member_KOB", required = true)
        protected String memberKOB;
        @XmlElement(name = "member_reference_number", required = true)
        protected String memberReferenceNumber;
        @XmlElement(name = "report_type", required = true)
        protected String reportType;
        @XmlElement(name = "output_format", required = true)
        protected String outputFormat;

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the productType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductType() {
            return productType;
        }

        /**
         * Sets the value of the productType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductType(String value) {
            this.productType = value;
        }

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserId(String value) {
            this.userId = value;
        }

        /**
         * Gets the value of the userPassword property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserPassword() {
            return userPassword;
        }

        /**
         * Sets the value of the userPassword property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserPassword(String value) {
            this.userPassword = value;
        }

        /**
         * Gets the value of the memberCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberCode() {
            return memberCode;
        }

        /**
         * Sets the value of the memberCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberCode(String value) {
            this.memberCode = value;
        }

        /**
         * Gets the value of the memberKOB property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberKOB() {
            return memberKOB;
        }

        /**
         * Sets the value of the memberKOB property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberKOB(String value) {
            this.memberKOB = value;
        }

        /**
         * Gets the value of the memberReferenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberReferenceNumber() {
            return memberReferenceNumber;
        }

        /**
         * Sets the value of the memberReferenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberReferenceNumber(String value) {
            this.memberReferenceNumber = value;
        }

        /**
         * Gets the value of the reportType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportType() {
            return reportType;
        }

        /**
         * Sets the value of the reportType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportType(String value) {
            this.reportType = value;
        }

        /**
         * Gets the value of the outputFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutputFormat() {
            return outputFormat;
        }

        /**
         * Sets the value of the outputFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutputFormat(String value) {
            this.outputFormat = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="general_fields">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="enquiry_amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="enquiry_purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="enquiry_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="type_of_entity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="class_of_activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="date_of_registration" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cmr_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="company_name">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="id">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="crn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="contact">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="address" maxOccurs="3">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="telephone" maxOccurs="3" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="directors">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="director" maxOccurs="3" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="relation_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="voter_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="passport_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="driving_licence_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="address">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="telephone" maxOccurs="3" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "generalFields",
        "companyName",
        "id",
        "contact",
        "directors"
    })
    public static class SearchData {

        @XmlElement(name = "general_fields", required = true)
        protected Request.SearchData.GeneralFields generalFields;
        @XmlElement(name = "company_name", required = true)
        protected Request.SearchData.CompanyName companyName;
        @XmlElement(required = true)
        protected Request.SearchData.Id id;
        @XmlElement(required = true)
        protected Request.SearchData.Contact contact;
        @XmlElement(required = true)
        protected Request.SearchData.Directors directors;

        /**
         * Gets the value of the generalFields property.
         * 
         * @return
         *     possible object is
         *     {@link Request.SearchData.GeneralFields }
         *     
         */
        public Request.SearchData.GeneralFields getGeneralFields() {
            return generalFields;
        }

        /**
         * Sets the value of the generalFields property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.SearchData.GeneralFields }
         *     
         */
        public void setGeneralFields(Request.SearchData.GeneralFields value) {
            this.generalFields = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link Request.SearchData.CompanyName }
         *     
         */
        public Request.SearchData.CompanyName getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.SearchData.CompanyName }
         *     
         */
        public void setCompanyName(Request.SearchData.CompanyName value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Request.SearchData.Id }
         *     
         */
        public Request.SearchData.Id getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.SearchData.Id }
         *     
         */
        public void setId(Request.SearchData.Id value) {
            this.id = value;
        }

        /**
         * Gets the value of the contact property.
         * 
         * @return
         *     possible object is
         *     {@link Request.SearchData.Contact }
         *     
         */
        public Request.SearchData.Contact getContact() {
            return contact;
        }

        /**
         * Sets the value of the contact property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.SearchData.Contact }
         *     
         */
        public void setContact(Request.SearchData.Contact value) {
            this.contact = value;
        }

        /**
         * Gets the value of the directors property.
         * 
         * @return
         *     possible object is
         *     {@link Request.SearchData.Directors }
         *     
         */
        public Request.SearchData.Directors getDirectors() {
            return directors;
        }

        /**
         * Sets the value of the directors property.
         * 
         * @param value
         *     allowed object is
         *     {@link Request.SearchData.Directors }
         *     
         */
        public void setDirectors(Request.SearchData.Directors value) {
            this.directors = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name"
        })
        public static class CompanyName {

            @XmlElement(required = true)
            protected String name;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="address" maxOccurs="3">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="telephone" maxOccurs="3" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address",
            "telephone"
        })
        public static class Contact {

            @XmlElement(required = true)
            protected List<Request.SearchData.Contact.Address> address;
            protected List<Request.SearchData.Contact.Telephone> telephone;

            /**
             * Gets the value of the address property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the address property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAddress().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Request.SearchData.Contact.Address }
             * 
             * 
             */
            public List<Request.SearchData.Contact.Address> getAddress() {
                if (address == null) {
                    address = new ArrayList<Request.SearchData.Contact.Address>();
                }
                return this.address;
            }

            /**
             * Gets the value of the telephone property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the telephone property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTelephone().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Request.SearchData.Contact.Telephone }
             * 
             * 
             */
            public List<Request.SearchData.Contact.Telephone> getTelephone() {
                if (telephone == null) {
                    telephone = new ArrayList<Request.SearchData.Contact.Telephone>();
                }
                return this.telephone;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "addressType",
                "addressLine1",
                "city",
                "state",
                "pinCode"
            })
            public static class Address {

                @XmlElement(required = true)
                protected String addressType;
                @XmlElement(required = true)
                protected String addressLine1;
                @XmlElement(required = true)
                protected String city;
                @XmlElement(required = true)
                protected String state;
                @XmlElement(required = true)
                protected String pinCode;

                /**
                 * Gets the value of the addressType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddressType() {
                    return addressType;
                }

                /**
                 * Sets the value of the addressType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddressType(String value) {
                    this.addressType = value;
                }

                /**
                 * Gets the value of the addressLine1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAddressLine1() {
                    return addressLine1;
                }

                /**
                 * Sets the value of the addressLine1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAddressLine1(String value) {
                    this.addressLine1 = value;
                }

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the state property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getState() {
                    return state;
                }

                /**
                 * Sets the value of the state property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setState(String value) {
                    this.state = value;
                }

                /**
                 * Gets the value of the pinCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPinCode() {
                    return pinCode;
                }

                /**
                 * Sets the value of the pinCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPinCode(String value) {
                    this.pinCode = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "telephoneType",
                "telephoneNum",
                "contactArea",
                "contactPrefix"
            })
            public static class Telephone {

                @XmlElement(required = true)
                protected String telephoneType;
                @XmlElement(name = "telephone_num", required = true)
                protected String telephoneNum;
                @XmlElement(name = "contact_area", required = true)
                protected String contactArea;
                @XmlElement(name = "contact_prefix", required = true)
                protected String contactPrefix;

                /**
                 * Gets the value of the telephoneType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTelephoneType() {
                    return telephoneType;
                }

                /**
                 * Sets the value of the telephoneType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTelephoneType(String value) {
                    this.telephoneType = value;
                }

                /**
                 * Gets the value of the telephoneNum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTelephoneNum() {
                    return telephoneNum;
                }

                /**
                 * Sets the value of the telephoneNum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTelephoneNum(String value) {
                    this.telephoneNum = value;
                }

                /**
                 * Gets the value of the contactArea property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContactArea() {
                    return contactArea;
                }

                /**
                 * Sets the value of the contactArea property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContactArea(String value) {
                    this.contactArea = value;
                }

                /**
                 * Gets the value of the contactPrefix property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContactPrefix() {
                    return contactPrefix;
                }

                /**
                 * Sets the value of the contactPrefix property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContactPrefix(String value) {
                    this.contactPrefix = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="director" maxOccurs="3" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="relation_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="voter_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="passport_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="driving_licence_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="address">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="telephone" maxOccurs="3" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "director"
        })
        public static class Directors {

            protected List<Request.SearchData.Directors.Director> director;

            /**
             * Gets the value of the director property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the director property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDirector().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Request.SearchData.Directors.Director }
             * 
             * 
             */
            public List<Request.SearchData.Directors.Director> getDirector() {
                if (director == null) {
                    director = new ArrayList<Request.SearchData.Directors.Director>();
                }
                return this.director;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="relation_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="dob" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="uid" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="voter_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="passport_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="driving_licence_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="address">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="telephone" maxOccurs="3" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "relationType",
                "dob",
                "gender",
                "pan",
                "uid",
                "voterId",
                "passportNum",
                "drivingLicenceId",
                "address",
                "telephone"
            })
            public static class Director {

                @XmlElement(required = true)
                protected String name;
                @XmlElement(name = "relation_type", required = true)
                protected String relationType;
                @XmlElement(required = true)
                protected String dob;
                @XmlElement(required = true)
                protected String gender;
                @XmlElement(required = true)
                protected String pan;
                @XmlElement(required = true)
                protected String uid;
                @XmlElement(name = "voter_id", required = true)
                protected String voterId;
                @XmlElement(name = "passport_num", required = true)
                protected String passportNum;
                @XmlElement(name = "driving_licence_id", required = true)
                protected String drivingLicenceId;
                @XmlElement(required = true)
                protected Request.SearchData.Directors.Director.Address address;
                protected List<Request.SearchData.Directors.Director.Telephone> telephone;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the relationType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRelationType() {
                    return relationType;
                }

                /**
                 * Sets the value of the relationType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRelationType(String value) {
                    this.relationType = value;
                }

                /**
                 * Gets the value of the dob property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDob() {
                    return dob;
                }

                /**
                 * Sets the value of the dob property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDob(String value) {
                    this.dob = value;
                }

                /**
                 * Gets the value of the gender property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGender() {
                    return gender;
                }

                /**
                 * Sets the value of the gender property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGender(String value) {
                    this.gender = value;
                }

                /**
                 * Gets the value of the pan property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPan() {
                    return pan;
                }

                /**
                 * Sets the value of the pan property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPan(String value) {
                    this.pan = value;
                }

                /**
                 * Gets the value of the uid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUid() {
                    return uid;
                }

                /**
                 * Sets the value of the uid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUid(String value) {
                    this.uid = value;
                }

                /**
                 * Gets the value of the voterId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getVoterId() {
                    return voterId;
                }

                /**
                 * Sets the value of the voterId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setVoterId(String value) {
                    this.voterId = value;
                }

                /**
                 * Gets the value of the passportNum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPassportNum() {
                    return passportNum;
                }

                /**
                 * Sets the value of the passportNum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPassportNum(String value) {
                    this.passportNum = value;
                }

                /**
                 * Gets the value of the drivingLicenceId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDrivingLicenceId() {
                    return drivingLicenceId;
                }

                /**
                 * Sets the value of the drivingLicenceId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDrivingLicenceId(String value) {
                    this.drivingLicenceId = value;
                }

                /**
                 * Gets the value of the address property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Request.SearchData.Directors.Director.Address }
                 *     
                 */
                public Request.SearchData.Directors.Director.Address getAddress() {
                    return address;
                }

                /**
                 * Sets the value of the address property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Request.SearchData.Directors.Director.Address }
                 *     
                 */
                public void setAddress(Request.SearchData.Directors.Director.Address value) {
                    this.address = value;
                }

                /**
                 * Gets the value of the telephone property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the telephone property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTelephone().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Request.SearchData.Directors.Director.Telephone }
                 * 
                 * 
                 */
                public List<Request.SearchData.Directors.Director.Telephone> getTelephone() {
                    if (telephone == null) {
                        telephone = new ArrayList<Request.SearchData.Directors.Director.Telephone>();
                    }
                    return this.telephone;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="addressType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="addressLine1" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="pinCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "addressType",
                    "addressLine1",
                    "city",
                    "state",
                    "pinCode"
                })
                public static class Address {

                    @XmlElement(required = true)
                    protected String addressType;
                    @XmlElement(required = true)
                    protected String addressLine1;
                    @XmlElement(required = true)
                    protected String city;
                    @XmlElement(required = true)
                    protected String state;
                    @XmlElement(required = true)
                    protected String pinCode;

                    /**
                     * Gets the value of the addressType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAddressType() {
                        return addressType;
                    }

                    /**
                     * Sets the value of the addressType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAddressType(String value) {
                        this.addressType = value;
                    }

                    /**
                     * Gets the value of the addressLine1 property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAddressLine1() {
                        return addressLine1;
                    }

                    /**
                     * Sets the value of the addressLine1 property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAddressLine1(String value) {
                        this.addressLine1 = value;
                    }

                    /**
                     * Gets the value of the city property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCity() {
                        return city;
                    }

                    /**
                     * Sets the value of the city property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCity(String value) {
                        this.city = value;
                    }

                    /**
                     * Gets the value of the state property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getState() {
                        return state;
                    }

                    /**
                     * Sets the value of the state property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setState(String value) {
                        this.state = value;
                    }

                    /**
                     * Gets the value of the pinCode property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPinCode() {
                        return pinCode;
                    }

                    /**
                     * Sets the value of the pinCode property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPinCode(String value) {
                        this.pinCode = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="telephoneType" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="telephone_num" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="contact_area" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="contact_prefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "telephoneType",
                    "telephoneNum",
                    "contactArea",
                    "contactPrefix"
                })
                public static class Telephone {

                    @XmlElement(required = true)
                    protected String telephoneType;
                    @XmlElement(name = "telephone_num", required = true)
                    protected String telephoneNum;
                    @XmlElement(name = "contact_area", required = true)
                    protected String contactArea;
                    @XmlElement(name = "contact_prefix", required = true)
                    protected String contactPrefix;

                    /**
                     * Gets the value of the telephoneType property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTelephoneType() {
                        return telephoneType;
                    }

                    /**
                     * Sets the value of the telephoneType property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTelephoneType(String value) {
                        this.telephoneType = value;
                    }

                    /**
                     * Gets the value of the telephoneNum property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTelephoneNum() {
                        return telephoneNum;
                    }

                    /**
                     * Sets the value of the telephoneNum property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTelephoneNum(String value) {
                        this.telephoneNum = value;
                    }

                    /**
                     * Gets the value of the contactArea property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContactArea() {
                        return contactArea;
                    }

                    /**
                     * Sets the value of the contactArea property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContactArea(String value) {
                        this.contactArea = value;
                    }

                    /**
                     * Gets the value of the contactPrefix property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getContactPrefix() {
                        return contactPrefix;
                    }

                    /**
                     * Sets the value of the contactPrefix property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setContactPrefix(String value) {
                        this.contactPrefix = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="enquiry_amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="enquiry_purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="enquiry_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="type_of_entity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="class_of_activity" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="date_of_registration" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cmr_flag" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "enquiryAmount",
            "enquiryPurpose",
            "enquiryType",
            "typeOfEntity",
            "classOfActivity",
            "dateOfRegistration",
            "cmrFlag"
        })
        public static class GeneralFields {

            @XmlElement(name = "enquiry_amount", required = true)
            protected String enquiryAmount;
            @XmlElement(name = "enquiry_purpose", required = true)
            protected String enquiryPurpose;
            @XmlElement(name = "enquiry_type", required = true)
            protected String enquiryType;
            @XmlElement(name = "type_of_entity", required = true)
            protected String typeOfEntity;
            @XmlElement(name = "class_of_activity", required = true)
            protected String classOfActivity;
            @XmlElement(name = "date_of_registration", required = true)
            protected String dateOfRegistration;
            @XmlElement(name = "cmr_flag", required = true)
            protected String cmrFlag;

            /**
             * Gets the value of the enquiryAmount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnquiryAmount() {
                return enquiryAmount;
            }

            /**
             * Sets the value of the enquiryAmount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnquiryAmount(String value) {
                this.enquiryAmount = value;
            }

            /**
             * Gets the value of the enquiryPurpose property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnquiryPurpose() {
                return enquiryPurpose;
            }

            /**
             * Sets the value of the enquiryPurpose property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnquiryPurpose(String value) {
                this.enquiryPurpose = value;
            }

            /**
             * Gets the value of the enquiryType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnquiryType() {
                return enquiryType;
            }

            /**
             * Sets the value of the enquiryType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnquiryType(String value) {
                this.enquiryType = value;
            }

            /**
             * Gets the value of the typeOfEntity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTypeOfEntity() {
                return typeOfEntity;
            }

            /**
             * Sets the value of the typeOfEntity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTypeOfEntity(String value) {
                this.typeOfEntity = value;
            }

            /**
             * Gets the value of the classOfActivity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClassOfActivity() {
                return classOfActivity;
            }

            /**
             * Sets the value of the classOfActivity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClassOfActivity(String value) {
                this.classOfActivity = value;
            }

            /**
             * Gets the value of the dateOfRegistration property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateOfRegistration() {
                return dateOfRegistration;
            }

            /**
             * Sets the value of the dateOfRegistration property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateOfRegistration(String value) {
                this.dateOfRegistration = value;
            }

            /**
             * Gets the value of the cmrFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCmrFlag() {
                return cmrFlag;
            }

            /**
             * Sets the value of the cmrFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCmrFlag(String value) {
                this.cmrFlag = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="crn" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pan",
            "cin",
            "crn",
            "tin"
        })
        public static class Id {

            @XmlElement(required = true)
            protected String pan;
            @XmlElement(required = true)
            protected String cin;
            @XmlElement(required = true)
            protected String crn;
            @XmlElement(required = true)
            protected String tin;

            /**
             * Gets the value of the pan property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPan() {
                return pan;
            }

            /**
             * Sets the value of the pan property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPan(String value) {
                this.pan = value;
            }

            /**
             * Gets the value of the cin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCin() {
                return cin;
            }

            /**
             * Sets the value of the cin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCin(String value) {
                this.cin = value;
            }

            /**
             * Gets the value of the crn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCrn() {
                return crn;
            }

            /**
             * Sets the value of the crn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCrn(String value) {
                this.crn = value;
            }

            /**
             * Gets the value of the tin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTin() {
                return tin;
            }

            /**
             * Sets the value of the tin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTin(String value) {
                this.tin = value;
            }

        }

    }

}
